update oay-webdav-ci

diff --git a/.github/workflows/oay_test_webdav.yml b/.github/workflows/oay_test_webdav.yml
--- a/.github/workflows/oay_test_webdav.yml
+++ b/.github/workflows/oay_test_webdav.yml
@@ -15,7 +15,7 @@
 # specific language governing permissions and limitations
 # under the License.
 
-name: Oay Test WebDAV
+name: Oay WebDAV Test
 
 on:
   push:
@@ -34,7 +34,7 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  oay-webdav-test:
+  oay-webdav-backend-fs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -52,19 +52,17 @@ jobs:
       - name: Build and Start WebDAV service
         run: |
           cargo build --package oay --bin webdav --release
-          nohup cargo run --package oay --bin webdav --release &
+          cargo run --package oay --bin webdav --release &
 
       - name: Run litmus tests
         run: |
           cd litmus-0.13
-          TESTS="http basic copymove" HTDOCS=htdocs TESTROOT=. ./litmus http://localhost:3000 >> litmus.log
-
-      - name: Check litmus test results
-        run: |
-          cat litmus-0.13/litmus.log
-          if grep -q "FATAL" litmus-0.13/litmus.log; then
-            echo "Tests failed"
-            exit 1
-          else
-            echo "All tests passed"
-          fi
+          TESTS="http basic copymove" HTDOCS=htdocs TESTROOT=. ./litmus http://localhost:3000 | while IFS= read -r line;
+          do
+            echo "$line"
+            if echo "$line" | grep -q "FATAL"; then
+              echo "Tests failed"
+              exit 1
+            fi
+          done
+          echo "All tests passed"
